soro.exe	:	soro.obj g_lio.obj mouse.obj
	link soro+g_lio+mouse;

soro.obj	:	soro.c g_lio.h mouse.h
	cl /c /AS /W4 /Oaxz soro.c | tee soro.err

g_lio.obj	:	g_lio.c
	cl /c /AS /W4 /Oaxz g_lio.c | tee g_lio.err

mouse.obj	:	mouse.c
	cl /c /AS /W4 /Oaxz mouse.c | tee mouse.err
